#!/usr/bin/ruby

version_file = File.read "src/polkaversion.h"
version_file =~ /POLKA_VERSION "(.*)"/
version = $1

puts "Release Polka version #{version}"

if ARGV.length != 1
  STDERR.puts "Usage: do_release <output_directory>"
  exit 1
end

output_dir = ARGV[0]

tarball = "polka-#{version}.tar.gz"

output_path = output_dir + "/" + tarball

tag = "v#{version}"

puts "Tagging #{tag}"

tag_cmd = "git tag -a #{tag} -m 'Version #{version}'"
system tag_cmd

puts "Writing to #{output_path}"

tar_cmd = "cd ..; tar czf #{output_path} --exclude-vcs --exclude TODO" +
  " --exclude do_release polka"
system tar_cmd

puts "Please push tag and upload tar ball."
